# --- XTrans train specific parameters ---

# determine whether meta_train or meta_test
meta_train: True

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

runner: "mt_parallel"
batch_size_run: 2
batch_size: 32

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "mt_new_task_repre_learner"
double_q: True
mixer: "mt_attn2_hx"
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64

agent: "mt_sotax"

# params about observation decomposition
id_length: 4
max_agent: 15

# params about task_encoder
dynamic_encoder: "mt_pooling"
dynamic_decoder: "mlp"
task_repre_dim: 32

state_latent_dim: 32  # 10

pretrain: True
dynamic_learning_end: 50000
save_repre: True
save_repre_interval: 1000
only_repre_learning: False

# params about trans mixing network
entity_embed_dim: 64
attn_embed_dim: 8

# mac
mac: "mt_new_task_repre_mac"

# params related with transfer training
breakpoint_training: False

save_model_interval: 200000

name: "new_task_repre_train"


# new method of task representation learning
# model_paths: ["single_task_models/2s3z/sota__whj_2s3z_first_2024-04-19_16-12-42", "single_task_models/3s5z/sota__whj_3s5z_first_2024-04-19_16-13-10", "single_task_models/3s5z_vs_3s6z/sota__whj_3s5z_vs_3s6z_first_2024-04-22_15-18-35"]
# model_paths: ["single_task_models/MMM/sota__whj_MMM_first_2024-04-17_19-14-32", "single_task_models/MMM2/sota__whj_MMM2_first_2024-04-17_19-29-49", "single_task_models/MMM4/sota__whj_MMM4_first_2024-04-17_19-30-31"]
model_paths: [
  "single_pre_train_model/3s3z",
  "single_pre_train_model/3s4z",
  "single_pre_train_model/3s5z",
  "single_pre_train_model/4s7z",
  "single_pre_train_model/2s3z_vs_2s4z",
  "single_pre_train_model/3s5z_vs_3s6z",
  "single_pre_train_model/3s6z_vs_3s7z"
]
single_task_runner: "single_runner"
single_task_mac: "basic_dc_mac"
single_task_agent: "sota"
single_task_learner: "dc_learner"
new_pretrain_method: True